### ISSUE TITLE
Crash while using auto-fill

### ISSUE THREAD

**Issue by andras-szuecs** [cromefire/jellyfin-mpp#1]
While using auto fill the app constantly crashes

**Comment by cromefire** [comment]
Yeah I forgot to archive the repository. I started new efforts at https://gitlab.com/cromefire_/jellyfin-cyborg but I'm waiting for some API improvements/documentation first before continuing it (the API client is one of the biggest blockers currently). Some of the improvements will probably already land in 10.6.
